// Generated by ego.
// DO NOT EDIT

package confirm
import (
"fmt"
"io"
)
var _ = fmt.Sprint("") // just so that we can keep the fmt import for now
//line actions_diff.ego:1
 func ActionsDiff(w io.Writer, ctx *ActionsDiffCtx) error  {
//line actions_diff.ego:2
_, _ = io.WriteString(w, "\n<html>\n<body>\n    <h2>Actions Diff</h2>\n    ")
//line actions_diff.ego:5
 if len(ctx.Actions) > 0 { 
//line actions_diff.ego:6
_, _ = io.WriteString(w, "\n    ")
//line actions_diff.ego:6
 for _, a := range ctx.Actions { 
//line actions_diff.ego:7
_, _ = io.WriteString(w, "\n    <div>\n    ")
//line actions_diff.ego:8
_, _ = fmt.Fprintf(w, "%v",  ctx.ActionString(a) )
//line actions_diff.ego:9
_, _ = io.WriteString(w, "\n    ")
//line actions_diff.ego:9
 if len(a.Diff) > 0 { 
//line actions_diff.ego:10
_, _ = io.WriteString(w, "\n    <br />\n    <div style=\"border:2px solid black\"><code style=\"margin:0px;padding:0px\"><pre>")
//line actions_diff.ego:11
_, _ = fmt.Fprintf(w, "%v",  ctx.ColorizeDiff(a.Diff) )
//line actions_diff.ego:11
_, _ = io.WriteString(w, "</pre></code>\n    </div>\n    ")
//line actions_diff.ego:13
 } 
//line actions_diff.ego:14
_, _ = io.WriteString(w, "\n    <hr />\n    ")
//line actions_diff.ego:15
 } 
//line actions_diff.ego:16
_, _ = io.WriteString(w, "\n    ")
//line actions_diff.ego:16
 } else { 
//line actions_diff.ego:17
_, _ = io.WriteString(w, "\n        <div><em>All Fine</em></div>\n    ")
//line actions_diff.ego:18
 } 
//line actions_diff.ego:19
_, _ = io.WriteString(w, "\n    <form action=\"/_close\" method=\"post\" accept-charset=\"utf-8\">\n        <p><input type=\"submit\" name=\"submit\" value=\"Close\"></p>\n        ")
//line actions_diff.ego:21
 if len(ctx.Actions) > 0 { 
//line actions_diff.ego:22
_, _ = io.WriteString(w, "\n            <strong>Please Type \"confirm\" to apply changes</strong>\n            <input type=\"text\" value=\"\" name=\"confirm\" id=\"confirm\"/>\n            <p><input type=\"submit\" name=\"submit\" value=\"Confirm\"></p>\n        ")
//line actions_diff.ego:25
 } 
//line actions_diff.ego:26
_, _ = io.WriteString(w, "\n    </form>\n</body>\n</html>\n")
return nil
}
